spring.application.name=spring-travel
spring.mvc.servlet.path=/api/v1
server.servlet.context-path=/spring-travel
spring.datasource.url=jdbc:postgresql://localhost:5432/best_travel
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
# --- Configuración de JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# -- Configuración de Email --
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_EMAIL}
spring.mail.password=${PASSWORD_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# -- Mongo DB --
spring.mongodb.authentication-database=admin
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=app_users
spring.mongodb.username=${USER_DB}
spring.mongodb.password=${PASSWORD_DB}
